version: '3.9'

services:
  backend:
    build:
      context: backend
    container_name: backend  
    ports:
      - "8089:8089"
    depends_on:
      - mongo
    networks:
        - local-network  
    restart: always
  frontend:
    build:
      context: frontend
    container_name: frontend  
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
        - local-network  
    restart: always    
  mongo:
      image: mongo:noble
      container_name: mongodb
      env_file:
      - backend/.env
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PWD}
        MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      volumes:
        - mongo-data:/data/db
      networks:
        - local-network

networks: 
    local-network:
      driver: bridge

volumes:
  mongo-data: